apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpanren
spec:
  replicas: 5
  selector:
    matchLabels:
       app: frontend
  template:
    metadata:
      name: testpod
      labels:
         app: frontend
    spec:
      containers:
      - name: container
        image: nginx
